services:
  _defaults:
    autowire: true
    autoconfigure: true

  Powernic\Bot\Emias\Subscription\Doctor\Service\:
    resource: '../../src/Emias/Subscription/Doctor/Service/*'

  Powernic\Bot\Emias\Subscription\Doctor\Repository\:
    resource: '../../src/Emias/Subscription/Doctor/Repository/*'

  Powernic\Bot\Emias\Subscription\EventListener\:
    resource: '../../src/Emias/Subscription/EventListener/*'


  app.emias.sub:
    class: Powernic\Bot\Emias\Subscription\CommandHandler\EmiasSubscriptionCommandHandler
    tags:
      - { name: 'app.command_handler', 'command': 'emiassub' }

  Powernic\Bot\Framework\Chat\Calendar\Selector\SelectorFactory:

  app.emias.sub.calendar:
    class: Powernic\Bot\Framework\Chat\Calendar\Handler\CalendarCallbackHandler
    arguments:
      $containerHandlerResolver: '@handler_resolver.container'
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{year}:{month}:{day}:{period}' }

  app.emias.sub.type:
    class: Powernic\Bot\Emias\Subscription\CallbackHandler\TypeCallbackHandler
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}' }

  app.emias.sub.receipt:
    class: Powernic\Bot\Emias\Subscription\Receipt\CallbackHandler\ReceiptSubscriptionCallbackHandler
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:receipt' }

  app.emias.sub.doctor:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\ConcreteSpeciality
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor' }

  app.emias.sub.doctor.type:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\DoctorType
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}' }

  app.emias.sub.doctor.alldoc:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\AllDoctorDateType
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:alldoc' }


  app.emias.sub.doctor.alldoc.allday:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\AllDoctorAllDay
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:alldoc:allday' }

  app.emias.sub.doctor.alldoc.oneday:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\AllDoctorOneDay
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:alldoc:oneday' }

  app.emias.sub.doctor.onedoc:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\ConcreteDoctor
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:onedoc' }


  app.emias.sub.doctor.onedoc.type:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\ConcreteDoctorDateType
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:onedoc:{doctorId}' }

  app.emias.sub.doctor.onedoc.allday:
    class: Powernic\Bot\Emias\Subscription\Doctor\CallbackHandler\OneDoctorAllDay
    tags:
      - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:onedoc:{doctorId}:allday' }

  #app.emias.sub.doctor.onedoc.oneday:
  #  class:
  #  tags:
  #    - { name: 'app.callback_handler', 'callback': 'emiassub:{id}:doctor:{speciality}:onedoc:{doctorId}:oneday' }

  #app.emias.sub.doctor.onedoc.oneday.text:
  #  class:
  #  tags:
  #    - { name: 'app.callback_handler', 'action': 'emiassub:{id}:doctor:{speciality}:onedoc:{doctorId}:oneday' }
#
