parameters:
  emias.api_url: '%env(EMIAS_API_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Powernic\Bot\Emias\Service\:
    resource: '../../src/Emias/Service/*'


  Powernic\Bot\Emias\Repository\:
    resource: '../../src/Emias/Repository/*'

  Powernic\Bot\Emias\Command\CheckEmiasSubscriptionCommand:
    tags:
      - { name: 'console.command' }
