services:
  _defaults:
    autowire: true
    autoconfigure: true

  Powernic\Bot\Emias\Service\:
    resource: '../../src/Emias/Service/*'

  Powernic\Bot\Emias\Repository\:
    resource: '../../src/Emias/Repository/*'

  Powernic\Bot\Emias\Service\EmiasService:
    arguments:
      $apiUrl : 'https://emias.info/api/new-cls/eim2'

  Powernic\Bot\Emias\Command\CheckEmiasSubscriptionCommand:
    tags:
      - { name: 'console.command' }
