services:
  translator.default:
    class: Symfony\Component\Translation\Translator
    arguments: [ "ru", null, "%kernel.cache_dir%/translations", false ]
    calls:
      - [ addLoader, [ "yaml", "@yaml_loader" ] ]
      - [ addResource, [ "yaml", "%kernel.project_dir%/translations/messages.ru.yaml", "ru" ] ]


  translator: '@translator.default'

  Symfony\Contracts\Translation\TranslatorInterface: '@translator'

  translator.formatter.default:
    class: Symfony\Component\Translation\Formatter\MessageFormatter

  translator.reader:
    class: Symfony\Component\Translation\Reader\TranslationReader

  Symfony\Component\Translation\Reader\TranslationReaderInterface: '@translation.reader'