services:
  _defaults:
    autowire: true

  app.bot:
    class: Powernic\Bot\Application
    public: true

  app.command_handler.emias.registration:
    class: Powernic\Bot\CommandHandler\Emias\EmiasRegistrationCommandHandler
    tags:
      - { name: 'app.command_handler', 'command': 'emias:reg' }



  Doctrine\ORM\EntityManager:
    factory: [ 'Powernic\Bot\Doctrine\EntityManagerFactory','create' ]
    arguments:
      $url: '%env(DATABASE_URL)%'

  TelegramBot\Api\Client:
    arguments:
      $token: '%env(TOKEN)%'

  TelegramBot\Api\BotApi:
    arguments:
      $token: '%env(TOKEN)%'
