<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container84VC60q\Powernic_Bot_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container84VC60q/Powernic_Bot_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container84VC60q.legacy');

    return;
}

if (!\class_exists(Powernic_Bot_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container84VC60q\Powernic_Bot_KernelDevDebugContainer::class, Powernic_Bot_KernelDevDebugContainer::class, false);
}

return new \Container84VC60q\Powernic_Bot_KernelDevDebugContainer([
    'container.build_hash' => '84VC60q',
    'container.build_id' => 'e6b3b1d1',
    'container.build_time' => 1637431038,
], __DIR__.\DIRECTORY_SEPARATOR.'Container84VC60q');
