<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
require __DIR__.'/Container84VC60q/Powernic_Bot_KernelDevDebugContainer.php';
require __DIR__.'/Container84VC60q/getTranslator_DefaultService.php';
require __DIR__.'/Container84VC60q/getApp_Emias_Policy_EditService.php';
require __DIR__.'/Container84VC60q/getApp_Emias_Policy_AddService.php';
require __DIR__.'/Container84VC60q/getClientService.php';
require __DIR__.'/Container84VC60q/getBotApiService.php';
require __DIR__.'/Container84VC60q/getCallbackTextHandlerService.php';
require __DIR__.'/Container84VC60q/getEntityManagerService.php';

$classes = [];
$classes[] = 'Doctrine\ORM\EntityManager';
$classes[] = 'Powernic\Bot\Framework\Doctrine\EntityManagerFactory';
$classes[] = 'Powernic\Bot\Framework\TextHandler\CallbackTextHandler';
$classes[] = 'Powernic\Bot\CallbackHandler\CallbackHandlerLoader';
$classes[] = 'Symfony\Component\DependencyInjection\ServiceLocator';
$classes[] = 'TelegramBot\Api\BotApi';
$classes[] = 'TelegramBot\Api\Client';
$classes[] = 'Powernic\Bot\Emias\Policy\CallbackHandler\AddCallbackHandler';
$classes[] = 'Symfony\Component\Validator\Validator\ValidatorInterface';
$classes[] = 'Symfony\Component\Validator\ValidatorBuilder';
$classes[] = 'Powernic\Bot\Emias\Policy\CallbackHandler\EditCallbackHandler';
$classes[] = 'Powernic\Bot\Kernel';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Symfony\Component\Translation\Translator';
$classes[] = 'Symfony\Component\Translation\Loader\YamlFileLoader';

Preloader::preload($classes);
